name: Link Checker

on:
  pull_request:
    types: [opened, synchronize, reopened]
  schedule:
    # Run weekly on Mondays at 3am UTC
    - cron: '0 3 * * 1'
  workflow_dispatch:

jobs:
  check-links:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Build site
      run: npm run build
    
    - name: Check for broken links
      uses: lycheeverse/lychee-action@v1
      with:
        # Check the built site
        args: >
          --verbose
          --no-progress
          --accept 200,204,206,301,302,303,307,308
          --timeout 20
          --max-retries 3
          --user-agent "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36"
          --exclude-mail
          --exclude "^http://localhost"
          --exclude "^http://127\.0\.0\.1"
          --exclude "linkedin\.com"
          --exclude "twitter\.com"
          ./dist
        fail: true
        jobSummary: true
        format: markdown
        
    - name: Comment PR with results
      if: github.event_name == 'pull_request' && failure()
      uses: actions/github-script@v7
      with:
        script: |
          const fs = require('fs');
          const linkCheckOutput = fs.readFileSync('./lychee/out.md', 'utf8');
          
          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: `## 🔗 Link Check Results\n\n${linkCheckOutput}`
          })