name: Structured Data Validation

on:
  pull_request:
    paths:
      - 'src/**/*.astro'
      - 'src/**/*.md'
      - 'src/**/*.mdx'
  workflow_dispatch:

jobs:
  validate-structured-data:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Build site
      run: npm run build
    
    - name: Install schema-dts for validation
      run: npm install -g schema-dts-gen
    
    - name: Validate JSON-LD structured data
      run: |
        echo "Checking for structured data in built HTML files..."
        
        # Find all HTML files
        find ./dist -name "*.html" -type f | while read -r file; do
          echo "Checking: $file"
          
          # Extract JSON-LD scripts and validate
          grep -o '<script type="application/ld+json">.*</script>' "$file" | \
          sed 's/<script type="application\/ld+json">//g' | \
          sed 's/<\/script>//g' | \
          while read -r jsonld; do
            if [ ! -z "$jsonld" ]; then
              echo "$jsonld" | npx ajv validate -s https://schema.org/version/latest/schemaorg-current-https.jsonld -d - || true
            fi
          done
        done
      continue-on-error: true
    
    - name: Check Open Graph tags
      run: |
        echo "Checking Open Graph meta tags..."
        
        # Basic Open Graph validation
        find ./dist -name "*.html" -type f | while read -r file; do
          if ! grep -q 'property="og:title"' "$file"; then
            echo "⚠️  Missing og:title in $file"
          fi
          if ! grep -q 'property="og:description"' "$file"; then
            echo "⚠️  Missing og:description in $file"
          fi
        done
      continue-on-error: true
    
    - name: Check Twitter Card tags
      run: |
        echo "Checking Twitter Card meta tags..."
        
        # Basic Twitter Card validation
        find ./dist -name "*.html" -type f | while read -r file; do
          if ! grep -q 'name="twitter:card"' "$file"; then
            echo "⚠️  Missing twitter:card in $file"
          fi
        done
      continue-on-error: true